services:
  promethei-base:
    image: durabilitylabs/nim-promethei-node:sha-ef6c958-dist-tests
    pull_policy: always
    restart: always
    environment:
      - NETWORK=devnet
      - PROMETHEI_DATA_DIR=/data
      - PROMETHEI_LOG_LEVEL=TRACE;warn:discv5,providers,manager,cache;warn:libp2p,multistream,switch,transport,tcptransport,semaphore,asyncstreamwrapper,lpstream,mplex,mplexchannel,noise,bufferstream,mplexcoder,secure,chronosstream,connection,connmanager,websock,ws-session,JSONRPC-CLIENT,JSONRPC-HTTP-CLIENT
      - PROMETHEI_API_BINDADDR=0.0.0.0
      - PROMETHEI_API_CORS_ORIGIN=*
      - PROMETHEI_STORAGE_QUOTA=10gb
      - NAT_PUBLIC_IP_AUTO=https://ip.archivist.storage
      - PROMETHEI_PERSISTENCE=true
      - PROMETHEI_ETH_PROVIDER=https://rpc.devnet.archivist.storage
      - MARKETPLACE_ADDRESS_FROM_URL=https://config.archivist.storage/devnet/marketplace
      # Fast cleanup:
      # TTL 1 hour
      # 10000 blocks every 30 seconds
      - PROMETHEI_BLOCK_TTL=3600
      - PROMETHEI_BLOCK_MI=30
      - PROMETHEI_BLOCK_MN=10000
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
    extra_hosts:
      - rpc-arbitrum:host-gateway
