<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Framework\PrometheiNetworkConfig\PrometheiNetworkConfig.csproj" />
    <ProjectReference Include="..\..\Framework\ArgsUniform\ArgsUniform.csproj" />
    <ProjectReference Include="..\..\Framework\BlockchainUtils\BlockchainUtils.csproj" />
    <ProjectReference Include="..\..\Framework\ChainFollowingApp\ChainFollowingApp.csproj" />
    <ProjectReference Include="..\..\Framework\GethConnector\GethConnector.csproj" />
    <ProjectReference Include="..\..\Framework\Logging\Logging.csproj" />
    <ProjectReference Include="..\..\ProjectPlugins\PrometheiContractsPlugin\PrometheiContractsPlugin.csproj" />
  </ItemGroup>

</Project>
