services:
  dist-test-run:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - PROMETHEIDOCKERIMAGE=durabilitylabs/nim-promethei-node:latest-dist-tests
      - BRANCH=main
      - KUBECONFIG=/opt/kubeconfig
      - LOGPATH=/opt/logs
    volumes:
      - /path/to/kubeconfig:/opt/kubeconfig
