<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="docker-compose.yaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Framework\PrometheiNetworkConfig\PrometheiNetworkConfig.csproj" />
    <ProjectReference Include="..\..\Framework\ArgsUniform\ArgsUniform.csproj" />
    <ProjectReference Include="..\..\Framework\MetricsServer\MetricsServer.csproj" />
    <ProjectReference Include="..\..\ProjectPlugins\PrometheiClient\PrometheiClient.csproj" />
    <ProjectReference Include="..\..\ProjectPlugins\GatewayClient\GatewayClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="docker-compose.yaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
